[features]
seeds = false
skip-lint = false
[programs.localnet]
vrf = "21yN3N5jquXxbPDSRZiqANhZsDQUAgQvz5vNysHXL3ut"
[programs.devnet]
vrf = "21yN3N5jquXxbPDSRZiqANhZsDQUAgQvz5vNysHXL3ut"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000

[test.validator]
url = "https://api.devnet.solana.com"


[[test.validator.clone]] # switchboardProgramId
address = "2TfB33aLaneQb5TNVwyDz3jSZXS6jdW2ARw1Dgf84XCG"

[[test.validator.clone]] # switchboardProgramDataAddress
address = "J4CArpsbrZqu1axqQ4AnrqREs3jwoyA1M5LMiQQmAzB9"

[[test.validator.clone]] # switchboardIdlAddress
address = "CKwZcshn4XDvhaWVH9EXnk3iu19t6t5xP2Sy2pD6TRDp"

[[test.validator.clone]] # switchboardProgramState
address = "BYM81n8HvTJuqZU1PmTVcwZ9G8uoji7FKM6EaPkwphPt"

[[test.validator.clone]] # switchboardVault
address = "FVLfR6C2ckZhbSwBzZY4CX7YBcddUSge5BNeGQv5eKhy"

[[test.validator.clone]] # switchboardMint
address = "So11111111111111111111111111111111111111112"

[[test.validator.clone]] # tokenWallet
address = "98noixB6NnabjgFKw9wgXtqVd9Xg6rmj5kEVMeCHUB5e"

[[test.validator.clone]] # oracleQueue
address = "AKmqAsAaGmQNAjukDFF1dV1bgf7R6N8ZPc8EFaYVxRMc"

[[test.validator.clone]] # oracleQueueAuthority
address = "AXrbiv8bmcJfscyYWjR8BMFvTUjmx7FSENCjtEx4NxFh"

[[test.validator.clone]] # oracleQueueBuffer
address = "CBr4sy264pSk2AWEoR7orL1S86EnwovLx5Jby5hvc8qR"

[[test.validator.clone]] # crank
address = "7KioKRwbvHJSUptFeY4w9hqSwXHNAfpbwCrxm4vR7jHR"

[[test.validator.clone]] # crankBuffer
address = "DqLqah6vmxMht13ziJc51weramDFgS2KBht4Uc2xNA8A"

[[test.validator.clone]] # oracle
address = "DJKzWaAVtq4AjrZB4e8BbpS3ngjrZZx3PFEGUEt5zEeL"

[[test.validator.clone]] # oracleAuthority
address = "AXrbiv8bmcJfscyYWjR8BMFvTUjmx7FSENCjtEx4NxFh"

[[test.validator.clone]] # oracleEscrow
address = "6eDr6kTX2Kd1SyTCENxgDUqpxNbuWEfATCfzRhMu8xjS"

[[test.validator.clone]] # oraclePermissions
address = "FRnRYARypjxFLw8ayZ5qKEUbXkCEW8tMnPnTRpvoyHRF"